# Generated by Django 5.2.1 on 2025-07-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='user_pk',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='following',
            name='user_pk',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
