version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - data_base
    env_file:
      - .env

  data_base:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A config.celery_conf worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "celery", "-A", "config.celery_conf", "inspect", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A config.celery_conf beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env



volumes:
  postgres_data: