# Generated by Django 5.2.1 on 2025-09-15 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('proxy', models.CharField(max_length=300)),
                ('is_valid', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='account.instagramaccount')),
            ],
            options={
                'unique_together': {('account', 'proxy'), ('temp_id', 'proxy')},
            },
        ),
    ]
