# Generated by Django 5.2.1 on 2025-12-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proxy', models.CharField(max_length=300)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=5)),
                ('used_slots', models.PositiveIntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Proxy',
        ),
    ]
