# Generated by Django 5.2.1 on 2025-08-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('account', 'proxy'), ('temp_id', 'proxy')},
        ),
    ]
