# Generated by Django 5.2.1 on 2025-06-05 10:45

import apps.task.models
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('post', 'Post'), ('story', 'Story')], max_length=10)),
                ('media_file', models.FileField(upload_to=apps.task.models.task_media_upload_to)),
                ('scheduled_time', models.DateTimeField()),
                ('state', django_fsm.FSMField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50, protected=True)),
                ('caption', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('disable_comments', models.PositiveSmallIntegerField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=0)),
                ('disable_like_and_view_counts', models.PositiveSmallIntegerField(choices=[(1, 'Enabled'), (0, 'Disabled')], default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('mention_username', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='account.instagramaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
