# Generated by Django 5.2.1 on 2025-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='client_settings',
            field=models.TextField(),
        ),
    ]
