# Generated by Django 5.2.1 on 2025-09-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='is_analyses_paused',
            field=models.BooleanField(default=False),
        ),
    ]
