# Generated by Django 5.2.1 on 2025-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_instagramaccount_is_analyses_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
