# Generated by Django 5.2.1 on 2025-12-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_instagramaccount_client_settings'),
        ('proxy', '0002_internalproxy_delete_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='internal_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_accounts', to='proxy.internalproxy'),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='client_pk',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='is_analyses_paused',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
