# Generated by Django 5.2.1 on 2025-12-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_instagramaccount_internal_proxy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='client_pk',
        ),
    ]
