# Generated by Django 5.2.1 on 2025-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('relation', 'Relation'), ('errors', 'Error')], max_length=20),
        ),
    ]
